
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A1D5023758B3B5858B15C407F6FA56F5'
    
_lr_action_items = {'WORD':([7,],[10,]),'QUOTE':([0,],[6,]),'HEADER':([0,],[2,]),'COMMA':([0,8,10,],[7,11,12,]),'INTEGER':([0,11,],[8,13,]),'$end':([0,1,2,3,4,5,6,9,12,13,],[-9,-3,-1,-4,0,-2,-8,-5,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[4,]),'speaker':([0,],[5,]),'episode':([0,],[1,]),'empty':([0,],[9,]),'quote':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> HEADER','start',1,'p_start','PLYsouthpark.py',40),
  ('start -> speaker','start',1,'p_start','PLYsouthpark.py',41),
  ('start -> episode','start',1,'p_start','PLYsouthpark.py',42),
  ('start -> quote','start',1,'p_start','PLYsouthpark.py',43),
  ('start -> empty','start',1,'p_start','PLYsouthpark.py',44),
  ('episode -> INTEGER COMMA INTEGER','episode',3,'p_episode','PLYsouthpark.py',49),
  ('speaker -> COMMA WORD COMMA','speaker',3,'p_speaker','PLYsouthpark.py',53),
  ('quote -> QUOTE','quote',1,'p_quote','PLYsouthpark.py',58),
  ('empty -> <empty>','empty',0,'p_empty','PLYsouthpark.py',62),
]
