
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '0944642092509D74F4AA26502D0120AE'
    
_lr_action_items = {'ALL':([0,],[2,]),'$end':([1,2,3,4,],[0,-3,-2,-1,]),'CPU':([0,],[3,]),'LINUX':([0,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LINUX','start',1,'p_start','PLYmpstat.py',39),
  ('start -> CPU','start',1,'p_start','PLYmpstat.py',40),
  ('start -> ALL','start',1,'p_start','PLYmpstat.py',41),
]
